# 1. We must use version 2.1 to enable orbs.
version: 2.1

# 2. Bring in the current version of the aws-serverless orb
orbs:
  # 3. We name our imported orb “sam”
  sam: circleci/aws-sam-serverless@3.2.0

jobs:
  build_app:
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - run: sam build
workflows:  
  build_and_deploy:
    jobs:
<<<<<<< HEAD
      - set-env:
      # 4. imported-name/job
=======
      - build_app:
          context: jklm-aws-demo
>>>>>>> 6c00b918b19752435cd1975ba227a7ce53374b0d
      - sam/deploy:
          context: jklm-aws-demo
          name: deploy-staging
          s3-bucket: my-s3-bucket
          stack-name: staging-stack
          template: template.yaml